<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Carbon;

class CategoriesTableSeeder extends Seeder
{
    public function run()
    {
        DB::table('categories')->insert([
            [
                'id' => 1,
                'parent_id' => null,
                'name' => 'Early Learning & Care',
                'slug' => 'early-learning-care',
                'subtitle' => 'Confident Choices for Early Care',
                'description' => 'Locate top-rated, trustworthy providers to support your child\'s development.',
                'providers_count' => 120,
                'icon' => 'fa-solid fa-child',
                'tags' => json_encode(['Daycare', 'Child-care', 'Preschool']),
                'image_url' => 'https://images.unsplash.com/photo-1650504148053-ae51b12dc1d4?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080',
                'sort_order' => 1,
                'status' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 2,
                'parent_id' => null,
                'name' => 'Schools & Education',
                'slug' => 'schools-education',
                'subtitle' => 'Invest in a Brighter Tomorrow',
                'description' => 'Choose from verified schools committed to excellence, character-building, and success.',
                'providers_count' => 35,
                'icon' => 'fa-solid fa-school',
                'tags' => json_encode(['Private Elementary', 'Private Middle School', 'Private High School']),
                'image_url' => 'https://images.unsplash.com/photo-1580582932707-520aed937b7b?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080',
                'sort_order' => 2,
                'status' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 3,
                'parent_id' => null,
                'name' => 'After-school & Tutoring',
                'slug' => 'after-school-tutoring',
                'subtitle' => 'Support Beyond the School Bell',
                'description' => 'Discover programs and tutoring that help your child thrive academically and creatively.',
                'providers_count' => 45,
                'icon' => 'fa-solid fa-book',
                'tags' => json_encode(['Afterschool Programs', 'Tutoring Services', 'Enrichment Activities']),
                'image_url' => 'https://images.unsplash.com/photo-1591123120675-6f7f1aae0e5b?q=80&w=1169&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
                'sort_order' => 3,
                'status' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 4,
                'parent_id' => null,
                'name' => 'Wellness & Family Support',
                'slug' => 'wellness-family-support',
                'subtitle' => 'Strength for Every Step of the Journey',
                'description' => 'Explore trusted programs that nurture the well-being of parents, children, and caregivers.',
                'providers_count' => 25,
                'icon' => 'fa-solid fa-heart',
                'tags' => json_encode(['Pediatric & Family Wellness', 'Therapy & Counseling', 'Yoga & Pilates', 'Parent Support Services']),
                'image_url' => 'https://images.unsplash.com/photo-1597075958693-75173d1c837f?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080',
                'sort_order' => 4,
                'status' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 5,
                'parent_id' => null,
                'name' => 'Events & Activities',
                'slug' => 'events-activities',
                'subtitle' => 'Play. Explore. Connect.',
                'description' => 'Find family-friendly events and programs that inspire joy, learning, and togetherness.',
                'providers_count' => 65,
                'icon' => 'fa-solid fa-lightbulb',
                'tags' => json_encode(['Birthday & Party Services', 'Camps (Summer, Holiday, Seasonal)', 'Family Events & Entertainment']),
                'image_url' => 'https://images.unsplash.com/photo-1687186511607-68b95444ea33?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080',
                'sort_order' => 5,
                'status' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            // Sub-categories examples
            [
                'id' => 6,
                'parent_id' => 1,
                'name' => 'Daycare Centers',
                'slug' => 'daycare-centers',
                'subtitle' => 'Safe and Nurturing Environments',
                'description' => 'Find licensed daycare centers that provide safe, nurturing environments for your children.',
                'providers_count' => 85,
                'icon' => 'fa-solid fa-baby',
                'tags' => json_encode(['Full Day Care', 'Part Time Care', 'Infant Care', 'Toddler Care']),
                'image_url' => 'https://images.unsplash.com/photo-1541692646447-34b4fcf81757?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&w=1080&q=80',
                'sort_order' => 1,
                'status' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 7,
                'parent_id' => 1,
                'name' => 'Preschool Programs',
                'slug' => 'preschool-programs',
                'subtitle' => 'Early Education Foundations',
                'description' => 'Quality preschool programs that build strong educational foundations for young learners.',
                'providers_count' => 35,
                'icon' => 'fa-solid fa-graduation-cap',
                'tags' => json_encode(['Montessori', 'Play Based', 'Academic Focus', 'Half Day Programs']),
                'image_url' => 'https://images.unsplash.com/photo-1503676260728-1c00da094a0b?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&w=1080&q=80',
                'sort_order' => 2,
                'status' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 8,
                'parent_id' => 3,
                'name' => 'Academic Tutoring',
                'slug' => 'academic-tutoring',
                'subtitle' => 'Boost Academic Performance',
                'description' => 'Professional tutoring services to help students excel in their academic subjects.',
                'providers_count' => 28,
                'icon' => 'fa-solid fa-calculator',
                'tags' => json_encode(['Math Tutoring', 'Science Help', 'Reading Support', 'Test Preparation']),
                'image_url' => 'https://images.unsplash.com/photo-1580894732444-8ecded7900cd?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&w=1080&q=80',
                'sort_order' => 1,
                'status' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 9,
                'parent_id' => 3,
                'name' => 'Sports & Recreation',
                'slug' => 'sports-recreation',
                'subtitle' => 'Active and Healthy Lifestyles',
                'description' => 'Sports programs and recreational activities to keep children active and healthy.',
                'providers_count' => 17,
                'icon' => 'fa-solid fa-baseball',
                'tags' => json_encode(['Soccer', 'Basketball', 'Swimming', 'Gymnastics', 'Martial Arts']),
                'image_url' => 'https://images.unsplash.com/photo-1551698618-1dfe5d97d256?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&w=1080&q=80',
                'sort_order' => 2,
                'status' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 10,
                'parent_id' => 4,
                'name' => 'Mental Health Services',
                'slug' => 'mental-health-services',
                'subtitle' => 'Supporting Emotional Well-being',
                'description' => 'Professional mental health services for children, teens, and families.',
                'providers_count' => 15,
                'icon' => 'fa-solid fa-brain',
                'tags' => json_encode(['Child Therapy', 'Family Counseling', 'Anxiety Support', 'Behavioral Therapy']),
                'image_url' => 'https://images.unsplash.com/photo-1576091160399-112ba8d25d1f?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&w=1080&q=80',
                'sort_order' => 1,
                'status' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
        ]);
    }
}