<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Carbon;

class CategoriesTableSeeder extends Seeder
{
    public function run()
    {
        DB::table('categories')->insert([
            // Main Categories
            [
                'id' => 1,
                'parent_id' => null,
                'name' => 'Education & Tutoring',
                'slug' => 'education-tutoring',
                'subtitle' => 'Academic Excellence and Growth',
                'description' => 'Comprehensive educational support from tutoring to full-time schooling for all ages.',
                'providers_count' => 75,
                'icon' => 'fa-solid fa-graduation-cap',
                'tags' => json_encode(['Tutoring', 'Schools', 'Test Prep', 'Language Learning']),
                'image_url' => 'https://images.unsplash.com/photo-1580894732444-8ecded7900cd?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&w=1080&q=80',
                'sort_order' => 1,
                'status' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 2,
                'parent_id' => null,
                'name' => 'After-School Programs',
                'slug' => 'after-school-programs',
                'subtitle' => 'Enrichment Beyond the Classroom',
                'description' => 'Diverse programs that nurture creativity, skills, and personal development after school.',
                'providers_count' => 60,
                'icon' => 'fa-solid fa-palette',
                'tags' => json_encode(['Arts', 'Sports', 'STEM', 'Enrichment', 'Childcare']),
                'image_url' => 'https://images.unsplash.com/photo-1591123120675-6f7f1aae0e5b?q=80&w=1169&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
                'sort_order' => 2,
                'status' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 3,
                'parent_id' => null,
                'name' => 'Wellness & Development',
                'slug' => 'wellness-development',
                'subtitle' => 'Supporting Growth and Well-being',
                'description' => 'Therapeutic and developmental services for children with diverse needs and abilities.',
                'providers_count' => 45,
                'icon' => 'fa-solid fa-heart-pulse',
                'tags' => json_encode(['Therapy', 'Counseling', 'Support', 'Neurodivergent', 'Development']),
                'image_url' => 'https://images.unsplash.com/photo-1576091160399-112ba8d25d1f?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&w=1080&q=80',
                'sort_order' => 3,
                'status' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 4,
                'parent_id' => null,
                'name' => 'Childcare & Early Learning',
                'slug' => 'childcare-early-learning',
                'subtitle' => 'Nurturing Young Minds',
                'description' => 'Safe, educational childcare options for infants, toddlers, and preschoolers.',
                'providers_count' => 90,
                'icon' => 'fa-solid fa-child',
                'tags' => json_encode(['Daycare', 'Preschool', 'Montessori', 'Babysitting', 'Childcare']),
                'image_url' => 'https://images.unsplash.com/photo-1650504148053-ae51b12dc1d4?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080',
                'sort_order' => 4,
                'status' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 5,
                'parent_id' => null,
                'name' => 'Sports, Fitness & Recreation',
                'slug' => 'sports-fitness-recreation',
                'subtitle' => 'Active Bodies, Healthy Minds',
                'description' => 'Sports, fitness, and recreational activities to promote physical health and teamwork.',
                'providers_count' => 55,
                'icon' => 'fa-solid fa-baseball-bat-ball',
                'tags' => json_encode(['Sports', 'Fitness', 'Martial Arts', 'Swimming', 'Outdoor']),
                'image_url' => 'https://images.unsplash.com/photo-1551698618-1dfe5d97d256?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&w=1080&q=80',
                'sort_order' => 5,
                'status' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 6,
                'parent_id' => null,
                'name' => 'Family Support Services',
                'slug' => 'family-support-services',
                'subtitle' => 'Strengthening Families Together',
                'description' => 'Comprehensive support services for parents and families navigating life\'s challenges.',
                'providers_count' => 30,
                'icon' => 'fa-solid fa-people-roof',
                'tags' => json_encode(['Parenting', 'Therapy', 'Support', 'Health', 'Nutrition']),
                'image_url' => 'https://images.unsplash.com/photo-1597075958693-75173d1c837f?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080',
                'sort_order' => 6,
                'status' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 7,
                'parent_id' => null,
                'name' => 'Events & Activities',
                'slug' => 'events-activities',
                'subtitle' => 'Play. Explore. Connect.',
                'description' => 'Family-friendly events, camps, and activities that create lasting memories.',
                'providers_count' => 65,
                'icon' => 'fa-solid fa-calendar-days',
                'tags' => json_encode(['Camps', 'Festivals', 'Entertainment', 'Workshops', 'Family Fun']),
                'image_url' => 'https://images.unsplash.com/photo-1687186511607-68b95444ea33?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080',
                'sort_order' => 7,
                'status' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],

            // Sub-categories for Education & Tutoring
            [
                'id' => 8,
                'parent_id' => 1,
                'name' => 'Academic Tutoring',
                'slug' => 'academic-tutoring',
                'subtitle' => 'Master Core Subjects',
                'description' => 'Individualized tutoring in math, science, reading, writing, and other academic subjects.',
                'providers_count' => 25,
                'icon' => 'fa-solid fa-calculator',
                'tags' => json_encode(['Math Tutoring', 'Science Help', 'Reading Support', 'Writing Skills']),
                'image_url' => 'https://images.unsplash.com/photo-1580894732444-8ecded7900cd?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&w=1080&q=80',
                'sort_order' => 1,
                'status' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 9,
                'parent_id' => 1,
                'name' => 'Test Preparation',
                'slug' => 'test-preparation',
                'subtitle' => 'Excel in Standardized Tests',
                'description' => 'Comprehensive test prep services for SAT, ACT, STAAR, and other standardized exams.',
                'providers_count' => 15,
                'icon' => 'fa-solid fa-pen-to-square',
                'tags' => json_encode(['SAT Prep', 'ACT Prep', 'STAAR Test', 'College Entrance']),
                'image_url' => 'https://images.unsplash.com/photo-1516321318423-f06f85e504b3?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&w=1080&q=80',
                'sort_order' => 2,
                'status' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 10,
                'parent_id' => 1,
                'name' => 'K-12 Schools',
                'slug' => 'k12-schools',
                'subtitle' => 'Quality Education Pathways',
                'description' => 'Elementary, middle, and high schools committed to academic excellence and student development.',
                'providers_count' => 20,
                'icon' => 'fa-solid fa-school',
                'tags' => json_encode(['Elementary School', 'Middle School', 'High School', 'Private Schools']),
                'image_url' => 'https://images.unsplash.com/photo-1580582932707-520aed937b7b?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080',
                'sort_order' => 3,
                'status' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 11,
                'parent_id' => 1,
                'name' => 'Language Learning',
                'slug' => 'language-learning',
                'subtitle' => 'Expand Linguistic Horizons',
                'description' => 'Foreign language instruction and bilingual programs for children of all ages.',
                'providers_count' => 15,
                'icon' => 'fa-solid fa-language',
                'tags' => json_encode(['Spanish', 'French', 'Mandarin', 'Bilingual Programs']),
                'image_url' => 'https://images.unsplash.com/photo-1523580494863-6f3031224c94?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&w=1080&q=80',
                'sort_order' => 4,
                'status' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],

            // Sub-categories for After-School Programs
            [
                'id' => 12,
                'parent_id' => 2,
                'name' => 'Arts & Crafts',
                'slug' => 'arts-crafts',
                'subtitle' => 'Creative Expression Unleashed',
                'description' => 'Hands-on art and craft programs that foster creativity and fine motor skills.',
                'providers_count' => 18,
                'icon' => 'fa-solid fa-paintbrush',
                'tags' => json_encode(['Painting', 'Drawing', 'Sculpture', 'Craft Projects']),
                'image_url' => 'https://images.unsplash.com/photo-1541961017774-22349e4a1262?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&w=1080&q=80',
                'sort_order' => 1,
                'status' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 13,
                'parent_id' => 2,
                'name' => 'Performing Arts',
                'slug' => 'performing-arts',
                'subtitle' => 'Center Stage for Young Talent',
                'description' => 'Music, dance, and theater programs that build confidence and performance skills.',
                'providers_count' => 16,
                'icon' => 'fa-solid fa-masks-theater',
                'tags' => json_encode(['Music Lessons', 'Dance Classes', 'Drama', 'Theater Arts']),
                'image_url' => 'https://images.unsplash.com/photo-1503095396549-807759245b35?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&w=1080&q=80',
                'sort_order' => 2,
                'status' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 14,
                'parent_id' => 2,
                'name' => 'Sports & Athletics',
                'slug' => 'sports-athletics',
                'subtitle' => 'Teamwork and Physical Fitness',
                'description' => 'Organized sports programs that teach teamwork, discipline, and athletic skills.',
                'providers_count' => 22,
                'icon' => 'fa-solid fa-basketball',
                'tags' => json_encode(['Team Sports', 'Individual Sports', 'Athletic Training']),
                'image_url' => 'https://images.unsplash.com/photo-1461896836934-ffe607ba8211?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&w=1080&q=80',
                'sort_order' => 3,
                'status' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 15,
                'parent_id' => 2,
                'name' => 'STEM Programs',
                'slug' => 'stem-programs',
                'subtitle' => 'Future Innovators and Problem Solvers',
                'description' => 'Robotics, coding, engineering, and science programs that spark curiosity and innovation.',
                'providers_count' => 14,
                'icon' => 'fa-solid fa-robot',
                'tags' => json_encode(['Robotics', 'Coding', 'Engineering', 'Science Clubs']),
                'image_url' => 'https://images.unsplash.com/photo-1550751827-4bd374c3f58b?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&w=1080&q=80',
                'sort_order' => 4,
                'status' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 16,
                'parent_id' => 2,
                'name' => 'Leadership & Enrichment',
                'slug' => 'leadership-enrichment',
                'subtitle' => 'Developing Future Leaders',
                'description' => 'Programs focused on leadership skills, character development, and personal growth.',
                'providers_count' => 12,
                'icon' => 'fa-solid fa-chess-queen',
                'tags' => json_encode(['Leadership', 'Character Building', 'Public Speaking', 'Life Skills']),
                'image_url' => 'https://images.unsplash.com/photo-1542621334-a254cf47733d?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&w=1080&q=80',
                'sort_order' => 5,
                'status' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 17,
                'parent_id' => 2,
                'name' => 'General After-School Care',
                'slug' => 'general-after-school-care',
                'subtitle' => 'Safe and Supervised Environments',
                'description' => 'Structured after-school care with homework help, snacks, and supervised activities.',
                'providers_count' => 28,
                'icon' => 'fa-solid fa-clock',
                'tags' => json_encode(['Childcare', 'Homework Help', 'Supervised Activities', 'Extended Care']),
                'image_url' => 'https://images.unsplash.com/photo-1541692646447-34b4fcf81757?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&w=1080&q=80',
                'sort_order' => 6,
                'status' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],

            // Sub-categories for Wellness & Development
            [
                'id' => 18,
                'parent_id' => 3,
                'name' => 'Speech Therapy',
                'slug' => 'speech-therapy',
                'subtitle' => 'Clear Communication Skills',
                'description' => 'Professional speech therapy services for articulation, language, and communication disorders.',
                'providers_count' => 12,
                'icon' => 'fa-solid fa-comments',
                'tags' => json_encode(['Articulation', 'Language Development', 'Communication Skills']),
                'image_url' => 'https://images.unsplash.com/photo-1576091160399-112ba8d25d1f?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&w=1080&q=80',
                'sort_order' => 1,
                'status' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 19,
                'parent_id' => 3,
                'name' => 'Occupational Therapy',
                'slug' => 'occupational-therapy',
                'subtitle' => 'Developing Life Skills',
                'description' => 'Therapy focused on developing fine motor skills, sensory processing, and daily living activities.',
                'providers_count' => 10,
                'icon' => 'fa-solid fa-hands',
                'tags' => json_encode(['Fine Motor Skills', 'Sensory Processing', 'Daily Living Skills']),
                'image_url' => 'https://images.unsplash.com/photo-1576671414121-aa0b82f00be0?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&w=1080&q=80',
                'sort_order' => 2,
                'status' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 20,
                'parent_id' => 3,
                'name' => 'Behavioral Therapy',
                'slug' => 'behavioral-therapy',
                'subtitle' => 'Positive Behavior Support',
                'description' => 'Evidence-based behavioral therapy for children with challenging behaviors and developmental disorders.',
                'providers_count' => 8,
                'icon' => 'fa-solid fa-brain',
                'tags' => json_encode(['ABA Therapy', 'Behavior Modification', 'Positive Support']),
                'image_url' => 'https://images.unsplash.com/photo-1591228127791-8e2eaef098b3?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&w=1080&q=80',
                'sort_order' => 3,
                'status' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 21,
                'parent_id' => 3,
                'name' => 'Mental Health & Counseling',
                'slug' => 'mental-health-counseling',
                'subtitle' => 'Emotional Well-being Support',
                'description' => 'Counseling and mental health services for children and adolescents facing emotional challenges.',
                'providers_count' => 15,
                'icon' => 'fa-solid fa-head-side-heart',
                'tags' => json_encode(['Child Counseling', 'Teen Therapy', 'Family Counseling', 'Anxiety', 'Depression']),
                'image_url' => 'https://images.unsplash.com/photo-1573497019940-1c28c88b4f3e?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&w=1080&q=80',
                'sort_order' => 4,
                'status' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],

            // Sub-categories for Childcare & Early Learning
            [
                'id' => 22,
                'parent_id' => 4,
                'name' => 'Daycare / Preschool',
                'slug' => 'daycare-preschool',
                'subtitle' => 'Structured Early Learning',
                'description' => 'Licensed daycare centers and preschools offering structured educational programs.',
                'providers_count' => 45,
                'icon' => 'fa-solid fa-building',
                'tags' => json_encode(['Licensed Care', 'Early Education', 'Structured Programs']),
                'image_url' => 'https://images.unsplash.com/photo-1541692646447-34b4fcf81757?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&w=1080&q=80',
                'sort_order' => 1,
                'status' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 23,
                'parent_id' => 4,
                'name' => 'Montessori',
                'slug' => 'montessori',
                'subtitle' => 'Child-Centered Education',
                'description' => 'Montessori programs focusing on self-directed learning and hands-on exploration.',
                'providers_count' => 18,
                'icon' => 'fa-solid fa-seedling',
                'tags' => json_encode(['Montessori Method', 'Self-Directed Learning', 'Hands-On Education']),
                'image_url' => 'https://images.unsplash.com/photo-1503676260728-1c00da094a0b?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&w=1080&q=80',
                'sort_order' => 2,
                'status' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 24,
                'parent_id' => 4,
                'name' => 'In-Home Childcare',
                'slug' => 'in-home-childcare',
                'subtitle' => 'Comfort of Home Care',
                'description' => 'Licensed home-based childcare providers offering personalized care in home settings.',
                'providers_count' => 22,
                'icon' => 'fa-solid fa-house',
                'tags' => json_encode(['Home Based', 'Small Groups', 'Personalized Care']),
                'image_url' => 'https://images.unsplash.com/photo-1616627561950-9d46d15f901c?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&w=1080&q=80',
                'sort_order' => 3,
                'status' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 25,
                'parent_id' => 4,
                'name' => 'Nanny & Babysitting Services',
                'slug' => 'nanny-babysitting-services',
                'subtitle' => 'Personalized In-Home Care',
                'description' => 'Professional nannies and babysitters providing individualized care in your home.',
                'providers_count' => 35,
                'icon' => 'fa-solid fa-user-nurse',
                'tags' => json_encode(['Nannies', 'Babysitters', 'In-Home Care', 'Flexible Hours']),
                'image_url' => 'https://images.unsplash.com/photo-1593113630400-ea4288922497?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&w=1080&q=80',
                'sort_order' => 4,
                'status' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],

            // Sub-categories for Sports, Fitness & Recreation
            [
                'id' => 26,
                'parent_id' => 5,
                'name' => 'Martial Arts',
                'slug' => 'martial-arts',
                'subtitle' => 'Discipline and Self-Defense',
                'description' => 'Karate, Taekwondo, Judo, and other martial arts teaching discipline and physical fitness.',
                'providers_count' => 15,
                'icon' => 'fa-solid fa-user-ninja',
                'tags' => json_encode(['Karate', 'Taekwondo', 'Judo', 'Self Defense', 'Discipline']),
                'image_url' => 'https://images.unsplash.com/photo-1594911472110-5ed344b0b17f?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&w=1080&q=80',
                'sort_order' => 1,
                'status' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 27,
                'parent_id' => 5,
                'name' => 'Gymnastics & Cheer',
                'slug' => 'gymnastics-cheer',
                'subtitle' => 'Strength, Flexibility, and Team Spirit',
                'description' => 'Gymnastics and cheerleading programs building strength, coordination, and teamwork.',
                'providers_count' => 12,
                'icon' => 'fa-solid fa-medal',
                'tags' => json_encode(['Gymnastics', 'Cheerleading', 'Tumbling', 'Flexibility']),
                'image_url' => 'https://images.unsplash.com/photo-1536922246285-4c8ee7ffb8a9?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&w=1080&q=80',
                'sort_order' => 2,
                'status' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 28,
                'parent_id' => 5,
                'name' => 'Swimming',
                'slug' => 'swimming',
                'subtitle' => 'Water Safety and Skills',
                'description' => 'Swimming lessons and aquatic programs focusing on water safety and stroke development.',
                'providers_count' => 18,
                'icon' => 'fa-solid fa-person-swimming',
                'tags' => json_encode(['Swim Lessons', 'Water Safety', 'Competitive Swimming']),
                'image_url' => 'https://images.unsplash.com/photo-1544551763-46a013bb70d5?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&w=1080&q=80',
                'sort_order' => 3,
                'status' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 29,
                'parent_id' => 5,
                'name' => 'Team Sports',
                'slug' => 'team-sports',
                'subtitle' => 'Building Teamwork and Skills',
                'description' => 'Soccer, basketball, football, and other team sports promoting cooperation and athletic development.',
                'providers_count' => 25,
                'icon' => 'fa-solid fa-people-group',
                'tags' => json_encode(['Soccer', 'Basketball', 'Football', 'Baseball', 'Teamwork']),
                'image_url' => 'https://images.unsplash.com/photo-1461896836934-ffe607ba8211?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&w=1080&q=80',
                'sort_order' => 4,
                'status' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],

            // Sub-categories for Family Support Services
            [
                'id' => 30,
                'parent_id' => 6,
                'name' => 'Parenting Workshops',
                'slug' => 'parenting-workshops',
                'subtitle' => 'Skills for Effective Parenting',
                'description' => 'Educational workshops and classes covering various parenting techniques and challenges.',
                'providers_count' => 8,
                'icon' => 'fa-solid fa-people-arrows',
                'tags' => json_encode(['Parent Education', 'Workshops', 'Parenting Techniques']),
                'image_url' => 'https://images.unsplash.com/photo-1584820927498-cfe5211fd8bf?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&w=1080&q=80',
                'sort_order' => 1,
                'status' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 31,
                'parent_id' => 6,
                'name' => 'Family Therapy',
                'slug' => 'family-therapy',
                'subtitle' => 'Strengthening Family Relationships',
                'description' => 'Therapeutic services addressing family dynamics, communication, and relationship challenges.',
                'providers_count' => 12,
                'icon' => 'fa-solid fa-hand-holding-heart',
                'tags' => json_encode(['Family Counseling', 'Relationship Therapy', 'Communication Skills']),
                'image_url' => 'https://images.unsplash.com/photo-1573497019940-1c28c88b4f3e?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&w=1080&q=80',
                'sort_order' => 2,
                'status' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],

            // Sub-categories for Events & Activities
            [
                'id' => 32,
                'parent_id' => 7,
                'name' => 'Camps',
                'slug' => 'camps',
                'subtitle' => 'Adventure and Learning',
                'description' => 'Summer, spring break, and holiday camps offering diverse activities and experiences.',
                'providers_count' => 35,
                'icon' => 'fa-solid fa-campground',
                'tags' => json_encode(['Summer Camp', 'Spring Break', 'Holiday Camp', 'Adventure']),
                'image_url' => 'https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&w=1080&q=80',
                'sort_order' => 1,
                'status' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 33,
                'parent_id' => 7,
                'name' => 'Family Entertainment',
                'slug' => 'family-entertainment',
                'subtitle' => 'Fun for the Whole Family',
                'description' => 'Bowling, trampoline parks, and other entertainment venues perfect for family outings.',
                'providers_count' => 20,
                'icon' => 'fa-solid fa-face-laugh-beam',
                'tags' => json_encode(['Bowling', 'Trampoline Parks', 'Family Fun', 'Entertainment']),
                'image_url' => 'https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&w=1080&q=80',
                'sort_order' => 2,
                'status' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 34,
                'parent_id' => 7,
                'name' => 'Educational Events & Workshops',
                'slug' => 'educational-events-workshops',
                'subtitle' => 'Learn and Explore Together',
                'description' => 'Interactive workshops and educational events for families to learn and explore new topics.',
                'providers_count' => 10,
                'icon' => 'fa-solid fa-lightbulb',
                'tags' => json_encode(['Workshops', 'Educational Events', 'Hands-On Learning']),
                'image_url' => 'https://images.unsplash.com/photo-1503676260728-1c00da094a0b?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&w=1080&q=80',
                'sort_order' => 3,
                'status' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
        ]);
    }
}